title = "gitleaks config"

[[rules]]
	description = "Env Var"
	regex = '''(?i)(api_key|apikey|secret|key|api|password|pw|host)=[0-9a-zA-Z-_{}]{4,120}'''

[[rules]]
	description = "Generic Credential"
	regex = '''(?i)(dbpasswd|dbuser|dbname|dbhost|api_key|apikey|secret|key|api|password|user|guid|hostname|pw|auth)(.{0,20})?['|"][0-9a-zA-Z-_!{}/=]{4,120}['|"]'''
	tags = ["key", "API", "generic"]

[[rules]]
	description = "WP-Config"
	regex='''define(.{0,20})?(DB_CHARSET|NONCE_SALT|LOGGED_IN_SALT|AUTH_SALT|NONCE_KEY|DB_HOST|DB_PASSWORD|AUTH_KEY|SECURE_AUTH_KEY|LOGGED_IN_KEY|DB_NAME|DB_USER)(.{0,20})?['|"].{10,120}['|"]'''
	tags = ["key", "API", "generic"]


[[rules]]
	description = "Pure Entropy"
	regex = '''['|"][0-9a-zA-Z-._{}$\/=]{40,120}['|"]'''
	entropies = [
        "5.0-5.6"
	]

[[rules]]
	description = "Entropy plus Generic Credential"
	regex = '''(?i)(api_key|apikey|secret|key|api|password|pw)'''
	entropies = [
        "5.2-5.5"
	]

[Global]
    file = '''(?i)(id_rsa|passwd|id_rsa.pub|pgpass|pem|key|shadow)'''

[whitelist]
	description = "image whitelists"
	file = '''(.*?)(jpg|gif|doc|pdf|bin)$'''

